[package]
name = "rascii_art"
version = "0.3.4"
authors = [ "KoBruhh", "RGBCube" ]
description = "Advanced ASCII Art Generator"
repository = "https://github.com/KoBruhh/RASCII"
keywords = [ "ascii" , "ascii-art", "art", "generator", "image", "image-to-ascii", "image-to-ascii-art", "image-to-text", "image-to-text-art", "text", "text-art", "text-to-ascii", "text-to-ascii-art", "text-to-image", "text-to-image-art", "text-to-text-art", "text-to-text-image", "text-to-text", "ai-art"]
license = "MIT"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.3.0", features = [ "derive" ] }
image = "0.24.6"
lazy_static = "1.4.0"
reqwest = { version = "0.11.18", features = [ "blocking", "json" ] }
serde = { version = "1.0.164", features = ["derive"] }
spinoff = { version = "0.7.0", features = ["arc"] }
tokio = { version = "1.28.2", features = ["full"] }
unicode-segmentation = "1.10.1"

[[bin]]
name = "rascii"
path = "src/main.rs"
